### ISSUE TITLE
Easy install with net2vis-docker

### ISSUE THREAD

**Issue by christianversloot** [viscom-ulm/Net2Vis#2]
Hi there,

Thanks a lot for creating such an extensive visualization app like Net2Vis!
However, for Windows machines, it's quite a hassle to install it, especially because it's difficult to install Cairo standalone and since workarounds have changed recently.
For this reason, I created a Docker Compose based setup called `net2vis-docker`, which essentially installs Net2Vis into two Linux based Docker containers, omitting the difficulties, and allowing to start the app with just one command.

It's available as an open source project here: https://github.com/christianversloot/net2vis-docker
I additionally wrote about it here, promoting Net2Vis in the process: https://www.machinecurve.com/index.php/2020/01/07/visualizing-keras-neural-networks-with-net2vis-and-docker/

Hope you like it, and keep up the good work! :)

Regards,
Chris

**Comment by Sparkier** [comment]
Hey Chris,

thank you for covering our work! We really appreciate if people like what we are doing. Also thank you for providing users an easier way to install Net2Vis.

I was working a lot on further improving the tool since you probably started your work, and now finally have a [website](http://viscom.net2vis.uni-ulm.de) where anyone can access Net2Vis. Maybe you can  update your blogpost and link to that?

Thank you for your great work!

**Comment by christianversloot** [comment]
> Maybe you can update your blogpost and link to that?

Sure, done :)
